### ISSUE TITLE
在vue组件中引用报错

### ISSUE THREAD

**Issue by JMengZhao** [blue0728/vue-city-picker#2]
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "data"

found in

---> <VueCityPicker>
       <Contents> at src\pages\shopOpen\content.vue
         <Root>

这是什么问题？怎么解决？

**Comment by wcy21k** [comment]
我也碰到了，目前在研究..

**Comment by W-Sprites** [comment]
原因应该是:data="data" 必须自定义 但是自定义了以后 原始数据就不展示了 去掉:data又报错
@JMengZhao @wcy21k  @blue0728 有什么好办法吗
